# Use the official Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the Python script to the container
COPY requirements_gymnasium.txt requirements_gymnasium.txt

# Install Xvfb and other dependencies
RUN apt-get update && apt-get install -y \
    xvfb freeglut3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements_gymnasium.txt
